# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: HTTP Request Action
        # You may pin to the exact commit or the version.
        # uses: fjogeleit/http-request-action@f986377e36f4e3d86c0c42523e02b844785182e9
      uses: fjogeleit/http-request-action@v1.9.1
      with:
        # Request URL
        url: https://play.orkes.io/api/metadata/workflow
        # Request Method
        method: PUT # optional, default is POST
        # Content Type
        contentType: application/json # optional
        # Request Body as JSON String
        data: postage_rate.json # optional, default is {}
        # Map of absolute file paths as JSON String
       # files: # optional, default is {}
        # A single absolute file path
        #file: postage_rate.json
        # Auth Username
       # username: # optional
        # Auth Password
       # password: # optional
        # Request Timeout in Sec
      #  timeout: # optional, default is 5000
        # Bearer Authentication Token
      #  bearerToken: # optional
        # Custom HTTP Headers
        customHeaders: 'X-Authorization: {{ secrets.PLAYGROUND_TOKEN }}'
        # optional
        # Prevent this Action to fail if the request respond without an response
       
