name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow maually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: authenticate
      id: authenticate
      uses: fjogeleit/http-request-action@v1.9.1
      with:  
        # Request URL
        url: 'https://play.orkes.io/api/token'
        # Request Method
        method: 'POST' # optional, default is POST
        # Content Type
        contentType: 'application/json' # optional
        data: '{"keyId": "${{ secrets.ORKES_WEATHER_KEY }}", "keySecret": "${{ secrets.ORKES_WEATHER_SECRET }}"}'
    - name: Show Response
      run: |
            echo "jwtToken=${{ ((steps.authenticate.outputs.response).token) }}" >> $GITHUB_ENV
    - name: update workflow
      uses: fjogeleit/http-request-action@v1.9.1
      with: # Set the secret as an input
          # Request URL
          url: 'https://play.orkes.io/api/metadata/workflow'
          # Request Method
          method: 'PUT' # optional, default is POST
          # Content Type
          contentType: 'application/json' # optional
          file: 'super_weather.json'
          customHeaders: '{"X-Authorization": "${{env.jwtToken}}" }'
#${{ env.jwtToken }}
#${{ secrets.playground_token}}
